import {test,expect,type Page} from '@playwright/test';
import {readFileSync,writeFileSync} from 'node:fs';
import path from 'node:path';
import {fixture} from './native-fixture';
test.setTimeout(90000);let f:ReturnType<typeof fixture>;let url:string;
test.beforeEach(async()=>{f=fixture();url=await f.start()});test.afterEach(async()=>{await f?.close()});
async function select(page:Page,id='HG-0005'){await page.goto(url);await page.getByRole('button',{name:'Все спецификации'}).click();await page.locator('.spec-row').filter({hasText:id}).click();await expect(page.locator('.document h1')).toHaveText(`Спецификация ${Number(id.slice(-1))}`)}
async function author(page:Page){await page.getByLabel('Ваше имя',{exact:true}).fill('Человек в тесте');if(await page.getByLabel('Версия проверенного результата',{exact:true}).count())await page.getByLabel('Версия проверенного результата',{exact:true}).fill('fixture-build-v1')}
test('HG56 S1 S2: explicit save, validation, cancel and navigation retain correct bytes',async({page})=>{
 await select(page);const initial=f.cli('spec-read','--id','HG-0005').change;await page.getByRole('button',{name:'Редактировать',exact:true}).click();expect((await page.locator('.editor legend').allTextContents()).join(' ')).not.toMatch(/HG-\d+-[RST]\d+/);await expect(page.getByLabel('Зачем это нужно',{exact:true})).toHaveCount(0);await page.getByLabel('Цель',{exact:true}).fill('');await page.getByRole('button',{name:'Сохранить изменения'}).click();await expect(page.getByRole('alert')).toContainText('Заполните');expect(f.cli('spec-read','--id','HG-0005').change.goal).toBe(initial.goal);
 await page.getByLabel('Цель',{exact:true}).fill('Сохранённое условие');await page.locator('.spec-row').filter({hasText:'HG-0002'}).click();await expect(page.getByRole('dialog')).toContainText('несохранённые');await page.getByRole('button',{name:'Продолжить редактирование'}).click();await expect(page.getByLabel('Цель',{exact:true})).toHaveValue('Сохранённое условие');
 await expect(page.getByLabel('Дано',{exact:true})).toHaveCount(0);await page.getByLabel('Условие готовности',{exact:true}).first().fill('Обновлённое условие готовности');await page.getByRole('button',{name:'Сохранить изменения'}).click();await expect(page.getByRole('status')).toContainText('Состояние сохранено');const after=f.cli('spec-read','--id','HG-0005').change;expect(after.goal).toBe('Сохранённое условие');expect(after.rationale).toBe(initial.rationale);expect(after.tasks).toEqual(initial.tasks);const expected=structuredClone(initial.operations);expected[0].requirement.scenarios[0].then='Обновлённое условие готовности';expect(after.operations).toEqual(expected);expect(after.evidence).toEqual(initial.evidence);await page.reload();await page.getByRole('button',{name:'В работе'}).click();await page.locator('.spec-row').filter({hasText:'HG-0005'}).click();await expect(page.locator('.document')).toContainText('Сохранённое условие');
 await page.getByRole('button',{name:'Редактировать',exact:true}).click();await page.getByLabel('Цель',{exact:true}).fill('Отменяемый текст');await page.getByRole('button',{name:'Отмена',exact:true}).click();await page.getByRole('button',{name:'Отменить правки',exact:true}).click();expect(f.cli('spec-read','--id','HG-0005').change.goal).toBe('Сохранённое условие');
});
test('HG56 S3: integrated and protected content cannot be edited through UI or API',async({page,request})=>{
 await select(page,'HG-0003');await expect(page.getByRole('button',{name:'Редактировать',exact:true})).toBeDisabled();const before=f.hash();const session=await(await request.get(url+'/api/session')).json();const read=f.cli('spec-read','--id','HG-0005');
 for(const [id,input] of [['HG-0005',{evidence:{}}],['HG-0003',{goal:'Переписать контракт'}]] as const){const r=await request.post(`${url}/api/specs/${id}/edit`,{headers:{Origin:url,'X-HighGrade-Token':session.token,'X-HighGrade-Api':'2'},data:{expected:read.store_sha256,input}});expect(r.ok()).toBeFalsy()}expect(f.hash()).toEqual(before);
});
test('HG56 S1: delayed write locks fields and navigation until confirmation',async({page})=>{
 await select(page);await page.getByRole('button',{name:'Редактировать',exact:true}).click();await page.getByLabel('Цель',{exact:true}).fill('Текст A');let release!:()=>void;let reached!:()=>void;const waiting=new Promise<void>(resolve=>release=resolve);const received=new Promise<void>(resolve=>reached=resolve);await page.route('**/api/specs/HG-0005/edit',async route=>{reached();await waiting;await route.fulfill({response:await route.fetch()})});await page.getByRole('button',{name:'Сохранить изменения'}).click();await received;await expect(page.getByLabel('Цель',{exact:true})).toBeDisabled();await expect(page.locator('.spec-row').filter({hasText:'HG-0002'})).toBeDisabled();await expect(page.getByRole('button',{name:'Обновить',exact:true})).toBeDisabled();release();await expect(page.getByRole('status')).toContainText('Состояние сохранено');expect(f.cli('spec-read','--id','HG-0005').change.goal).toBe('Текст A');
});
test('HG56 S4 S5: local CAS, conflict comparison and lost response never blindly retry writes',async({page})=>{
 await select(page);await page.getByRole('button',{name:'Редактировать',exact:true}).click();await page.getByLabel('Цель',{exact:true}).fill('Независимая правка A');f.edit('HG-0002',{goal:'Другая спека'});await page.getByRole('button',{name:'Сохранить изменения'}).click();await expect(page.getByRole('status')).toContainText('Состояние сохранено');
 await page.getByRole('button',{name:'Редактировать',exact:true}).click();await page.getByLabel('Цель',{exact:true}).fill('Моя правка A');f.edit('HG-0005',{goal:'Внешняя правка B'});await page.getByRole('button',{name:'Сохранить изменения'}).click();await expect(page.getByRole('alert')).toContainText('LocalConflict');await expect(page.getByLabel('Цель',{exact:true})).toHaveValue('Моя правка A');expect(f.cli('spec-read','--id','HG-0005').change.goal).toBe('Внешняя правка B');await page.getByRole('button',{name:'Перечитать и сравнить'}).click();await expect(page.getByText('Сейчас в проекте')).toBeVisible();await page.getByRole('button',{name:'Применить мои поля к новой базе'}).click();await page.getByRole('button',{name:'Сохранить изменения'}).click();await expect(page.getByRole('status')).toContainText('Состояние сохранено');
 await page.getByRole('button',{name:'Редактировать',exact:true}).click();await page.getByLabel('Цель',{exact:true}).fill('Ответ потерян, запись состоялась');let writes=0;await page.route('**/api/specs/HG-0005/edit',async route=>{writes++;await route.fetch();await route.abort()});await page.getByRole('button',{name:'Сохранить изменения'}).click();await expect(page.getByRole('alert')).toBeVisible();expect(writes).toBe(1);await expect(page.getByRole('button',{name:'Сохранить изменения'})).toBeDisabled();await page.getByRole('button',{name:'Перечитать и сравнить'}).click();await page.getByRole('button',{name:'Использовать версию проекта'}).click();expect(writes).toBe(1);expect(f.cli('spec-read','--id','HG-0005').change.goal).toBe('Ответ потерян, запись состоялась');
});
test('HG56 S6 S7: agreement is bound to visible content and actual baseline diff',async({page})=>{
 f.edit('HG-0002',{goal:'Цель 2: зависит от HG-0003-R1'});f.handoff('HG-0002','requirements','requirements-initial');await select(page,'HG-0002');await page.getByRole('button',{name:'Согласовать требования',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('не разрешение выполнять работу');await author(page);await page.getByRole('button',{name:'Подтвердить',exact:true}).click();await expect(page.getByRole('status')).toContainText('Состояние сохранено');f.edit('HG-0002',{goal:'Редакция B: зависит от HG-0004-R1'});f.handoff('HG-0002','requirements','requirements-B');await page.getByRole('button',{name:'Обновить',exact:true}).click();await page.getByRole('button',{name:'Посмотреть изменения',exact:true}).click();await expect(page.locator('[data-diff-section]')).toContainText('Цель 2');await expect(page.locator('[data-diff-section]')).toContainText('Редакция B');await expect(page.locator('[data-diff-section] .diff-grid>div').nth(0)).toContainText('HG-0003-R1');await expect(page.locator('[data-diff-section] .diff-grid>div').nth(1)).toContainText('HG-0004-R1');
 await page.getByRole('button',{name:'Редактировать',exact:true}).click();await page.getByLabel('Цель',{exact:true}).fill('Несохранённое');await expect(page.getByRole('button',{name:'Согласовать требования',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Отмена',exact:true}).click();await page.getByRole('button',{name:'Отменить правки',exact:true}).click();await page.getByRole('button',{name:'Согласовать требования',exact:true}).click();await author(page);await page.getByRole('button',{name:'Подтвердить',exact:true}).click();await expect(page.getByRole('status')).toContainText('Состояние сохранено');const row=f.row('HG-0002');expect(row.history.filter((r:any)=>r.response?.decision==='accepted')).toHaveLength(2);expect(f.cli('spec-read','--id','HG-0002').change.tasks[0].done).toBe(false);
});
test('HG56 S8 S9: result readiness and required return explanation are checked at write time',async({page})=>{
 await select(page,'HG-0003');await page.getByRole('button',{name:'Принять результат',exact:true}).click();await page.getByLabel('Ваше имя',{exact:true}).fill('Человек в тесте');await page.getByRole('button',{name:'Подтвердить',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Git SHA');expect(f.cli('spec-read','--id','HG-0003').change.acceptance).toHaveLength(0);await author(page);await page.getByRole('button',{name:'Вернуть на доработку'}).click();await expect(page.getByRole('alert')).toContainText('пояснение');writeFileSync(path.join(f.root,'proof.txt'),'Changed proof');await page.getByRole('button',{name:'Подтвердить',exact:true}).click();await expect(page.getByRole('alert')).toContainText('DecisionStale');expect(f.cli('spec-read','--id','HG-0003').change.acceptance).toHaveLength(0);
});
test('HG56 S7: a changed visible revision cannot be agreed through an already open dialog',async({page})=>{
 await select(page,'HG-0002');await page.getByRole('button',{name:'Согласовать требования',exact:true}).click();await author(page);f.edit('HG-0002',{goal:'Невидимая редакция'});await page.getByRole('button',{name:'Подтвердить',exact:true}).click();await expect(page.getByRole('alert')).toContainText('StoreConflict');expect(f.row('HG-0002').history[0].response).toBeNull();await expect(page.getByLabel('Ваше имя',{exact:true})).toHaveValue('Человек в тесте');
});
test('HG56 S8 S10: accepted result stays visible and only answered question closes',async({page})=>{
 f.handoff('HG-0001','question','question-2');await select(page,'HG-0001');await page.locator('.decision').getByRole('button').click();await author(page);await page.getByLabel('Ответ',{exact:true}).fill('Сохраняем введённый текст');await page.getByRole('button',{name:'Сохранить ответ',exact:true}).click();await expect(page.getByRole('status')).toContainText('Состояние сохранено');expect(f.row('HG-0001').requests).toHaveLength(1);
 await page.locator('.spec-row').filter({hasText:'HG-0003'}).click();await page.getByRole('button',{name:'Принять результат',exact:true}).click();await author(page);await page.getByRole('button',{name:'Подтвердить',exact:true}).click();await expect(page.getByRole('status')).toContainText('Состояние сохранено');await expect(page.locator('.document h1')).toHaveText('Спецификация 3');expect(f.row('HG-0003').category).toBe('completed');expect(f.cli('spec-read','--id','HG-0003').change.acceptance.at(-1).verified_revision).toBe('fixture-build-v1');
 f.handoff('HG-0003','result','result-return');await page.getByRole('button',{name:'Обновить',exact:true}).click();await page.getByRole('button',{name:'Принять результат',exact:true}).click();await author(page);await page.getByLabel('Комментарий',{exact:true}).fill('Нужно уточнить результат');await page.getByRole('button',{name:'Вернуть на доработку'}).click();await expect(page.getByRole('status')).toContainText('Состояние сохранено');expect(f.row('HG-0003').human).toBe('needs_changes');
});
