import {decisionReason} from './decisionCopy';
import {useEffect,useState} from 'react';
import {api,readSpec,errorText,type Handoff,type ReadResult,type Session} from '@/api/client';
import {Button} from '@/components/ui/button';import {Input} from '@/components/ui/input';import {Textarea} from '@/components/ui/textarea';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter} from '@/components/ui/dialog';
export function DecisionDialog({request,read,session,onClose,onSaved,onBusy}:{onBusy:(v:boolean)=>void;request:Handoff;read:ReadResult;session:Session;onClose:()=>void;onSaved:()=>Promise<void>}){
 const [verifiedRevision,setVerifiedRevision]=useState('');
 const [author,setAuthor]=useState('');const [comment,setComment]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [uncertain,setUncertain]=useState(false);
 useEffect(()=>{onBusy(busy);return()=>onBusy(false)},[busy,onBusy]);
 const title=request.kind==='question'?'Ответить на вопрос':request.kind==='requirements'?'Согласовать требования':'Принять результат';
 const decide=async(decision:string)=>{if(request.kind==='result'&&!verifiedRevision.trim()){setError('Укажите Git SHA или неизменяемый build ID проверенной реализации.');return}if(!author.trim()){setError('Укажите ваше имя.');return}if((decision==='answer'||decision==='needs_changes')&&!comment.trim()){setError('Добавьте ответ или пояснение.');return}setBusy(true);setError('');try{
  await api(`/api/specs/${read.change.id}/attention`,{method:'POST',headers:{'Content-Type':'application/json','X-HighGrade-Token':session.token},body:JSON.stringify({expected:read.store_sha256,input:{action:'respond',request_id:request.id,content_sha256:request.content_sha256,decision,author:author.trim(),comment,verified_revision:request.kind==='result'?verifiedRevision.trim():''}})});
  await onSaved();onClose();
 }catch(e){setError(errorText(e));setUncertain(true)}finally{setBusy(false)}};
 const inspect=async()=>{setBusy(true);try{const current=await readSpec(read.change.id);const response=(current.change as unknown as {attention?:{requests:Handoff[]}}).attention?.requests.find(r=>r.id===request.id)?.response;if(response){setError(`В проекте записано решение: ${response.decision}; автор: ${response.author}. Обновите документ.`)}else setError('Ответ не найден в текущем состоянии. Закройте окно и обновите документ перед новой попыткой.')}catch(e){setError(errorText(e))}finally{setBusy(false)}};
 return <Dialog open onOpenChange={open=>{if(!open&&!busy)onClose()}}><DialogContent className={request.kind==='result'?'decision-dialog-compact':undefined}><DialogHeader><DialogTitle>{title}</DialogTitle><DialogDescription>{request.kind==='requirements'?'Согласие относится только к показанному содержанию. Это не разрешение выполнять работу и не запуск агента.':request.kind==='result'?'Подтвердите проверенную версию.':'Ответ закроет только этот записанный вопрос.'}</DialogDescription></DialogHeader>{decisionReason(request)&&<p className="source-text">{decisionReason(request)}</p>}{request.kind==='result'&&<><label htmlFor="verified-revision">Версия проверенного результата</label><Input id="verified-revision" placeholder="Git SHA или неизменяемый build ID" value={verifiedRevision} onChange={e=>setVerifiedRevision(e.target.value)} disabled={busy}/></>}<label htmlFor="decision-author">Ваше имя</label><Input id="decision-author" disabled={busy} value={author} onChange={e=>setAuthor(e.target.value)}/><label htmlFor="decision-comment">{request.kind==='question'?'Ответ':'Комментарий'}</label><Textarea id="decision-comment" disabled={busy} value={comment} onChange={e=>setComment(e.target.value)}/>{error&&<div role="alert" className="notice error"><p>{error}</p>{uncertain&&<Button variant="outline" onClick={inspect} disabled={busy}>Проверить состояние решения</Button>}</div>}<DialogFooter><Button variant="outline" onClick={onClose} disabled={busy}>Закрыть</Button>{request.kind!=='question'&&<Button variant="outline" onClick={()=>decide('needs_changes')} disabled={busy||uncertain}>Вернуть на доработку</Button>}<Button onClick={()=>decide(request.kind==='question'?'answer':'accepted')} disabled={busy||uncertain}>{request.kind==='question'?'Сохранить ответ':'Подтвердить'}</Button></DialogFooter></DialogContent></Dialog>;
}
