from record import *
case='empty-project'; root=WORK/case
a=run(case,'20-read-before-tag','spec-read','--id','HG-0001','--view','editable',allowed=(0,))
run(case,'21-tag-library','spec-tag-set','--id','library','--title','Каталог книг','--description','Предметные возможности личного каталога книг','--expected',a['result']['store_sha256'],allowed=(0,))
a=run(case,'22-read-before-edit','spec-read','--id','HG-0001','--view','editable',allowed=(0,))
patch={'tags':['library'],'goal':'Один пользователь добавляет название и автора прочитанной книги и видит локальный список.','rationale':'Synthetic fixture owner задал первый полезный результат; текущий init только подготавливает требования.','scope':'Первая версия: добавление и просмотр, без сети, аккаунтов и внешних интеграций. Реализация и выбор стека не входят в init; будущие области кода и тестов ещё не назначены.','questions':['Какой локальный интерфейс нужен и как запускать его на выбранной среде?','Должны ли данные сохраняться между запусками и где храниться?','Какие стек, путь реализации и штатный runner выбрать перед Work?'],'operations':[{'action':'add','requirement':{'id':'HG-0001-R1','title':'Добавление и просмотр книг','statement':'Первый полезный результат SHALL позволять одному пользователю добавить название и автора прочитанной книги и увидеть их в локальном списке, без сети и аккаунтов.','scenarios':[{'id':'HG-0001-S1','given':'Локальный каталог открыт одним пользователем; список пуст. Конкретный интерфейс и хранение уточняются до реализации.','when':'Пользователь добавляет книгу с названием «Маяк» и автором «Н. Петров».','then':'В списке видны введённые название и автор; действие не требует сети или аккаунта.','verification':'До Work выбрать фактический интерфейс и штатный runner; будущая проверка выполняет добавление и наблюдает список и отсутствие сетевой зависимости. В init этот сценарий не исполнялся.'}]}}],'tasks':[{'id':'HG-0001-T1','description':'Уточнить локальный интерфейс, хранение и runner в этом же ID до реализации.','done':False},{'id':'HG-0001-T2','description':'После отдельного поручения реализовать добавление названия/автора и просмотр локального списка.','done':False},{'id':'HG-0001-T3','description':'Проверить добавление и просмотр выбранным штатным способом без сетевой зависимости.','done':False}]}
write(EVIDENCE/case,'inputs/23-spec-content.json',json.dumps(patch,ensure_ascii=False,indent=2)+'\n');write(root,'.highgrade/local/inputs/23-spec-content.json',json.dumps(patch,ensure_ascii=False,indent=2)+'\n')
run(case,'23-spec-content','spec-edit','--id','HG-0001','--input','.highgrade/local/inputs/23-spec-content.json','--expected',a['result']['store_sha256'],allowed=(0,))
run(case,'24-spec-validate','spec-validate','--id','HG-0001')
p=root/'.highgrade/project/INSTRUCTIONS.md';s=p.read_text().replace('Подготовить первоначальную спеку каталога книг; после init уточнить тот же назначенный CLI ID, его интерфейс, хранение и runner.','Через CLI подготовлен предметный черновик HG-0001 «Локальное добавление и просмотр прочитанных книг». После init первым уточнить этот же HG-0001: интерфейс, хранение и runner; эти вопросы находятся в самой спеке.')
write(root,'.highgrade/project/INSTRUCTIONS.md',s)
for case in ('empty-project','owner-docs'):
 run(case,'25-inspect','inspect')
 run(case,'26-doctor','doctor')
 if case=='empty-project': run(case,'27-doctor-spec-read','doctor','--action','spec-read')
