"""Render complete skills from their single editable procedure source."""
import argparse
import hashlib
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
KIT = ROOT / 'kit'

def render(path):
    old = path.read_text(encoding='utf-8-sig')
    front = old.split('---', 2)[1].strip()
    front = front.replace('Создать или обновить OpenSpec-изменение', 'Создать или обновить нативную спецификацию High Grade')
    name = path.parent.name.removeprefix('highgrade-')
    procedure = KIT / 'procedures' / (name + '.md')
    body = procedure.read_text(encoding='utf-8-sig').strip()
    # References are resolved from the active release, not from the profile's
    # skill directory. Plain paths work in both the source and installed skill.
    def reference(m):
        label, target = m.groups()
        if '://' in target:
            return m.group(0)
        target = target[3:] if target.startswith('../') else 'procedures/' + target
        return f'{label} (`{target}` внутри активного выпуска)'
    body = re.sub(r'\[([^\]]+)\]\(([^)]+)\)', reference, body)
    return f'''---
{front}
---

<!-- Generated by scripts/render-skills.py from procedures/{name}.md. -->

Профиль определяется по расположению `<профиль>/.agents/skills/highgrade-{name}/SKILL.md`; корень проекта — по workspace пользователя. Активный выпуск указан в `<профиль>/.highgrade/global/active.json`; его CLI и материалы находятся в `<профиль>/.highgrade/global/releases/<release>/`. На первом входе прочитай `rules.md` выпуска, AGENTS и местную инструкцию проекта; проверь `global-status --profile <профиль>` CLI этого выпуска. Переиспользуй проверенный контекст по rules.md. Отсутствие проектной инструкции при init ожидаемо. При повреждении установки назови фактическую ошибку. Ниже уже находится инструкция этапа; `procedures/{name}.md` повторно читать не нужно. Все указанные пути материалов относятся к корню активного выпуска.

{body}
'''

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    changed = []
    for path in sorted((KIT / 'skills').glob('highgrade-*/SKILL.md')):
        expected = render(path)
        if path.read_text(encoding='utf-8-sig') != expected:
            changed.append(str(path.relative_to(ROOT)))
            if not args.check:
                path.write_text(expected, encoding='utf-8', newline='\n')
    manifest_path = KIT / 'manifest.json'
    manifest = json.loads(manifest_path.read_text(encoding='utf-8-sig'))
    hashes = {rel: hashlib.sha256((KIT / rel).read_bytes()).hexdigest() for rel in manifest['files']}
    if args.check:
        if changed or hashes != manifest['files']:
            raise SystemExit('Stale generated skills or manifest: ' + ', '.join(changed))
        print('Skills and manifest are current')
    else:
        manifest['files'] = hashes
        manifest_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + '\n', encoding='utf-8', newline='\n')
        print(f'Rendered {len(changed)} skills; refreshed manifest')

if __name__ == '__main__':
    main()
